# Site settings
title: ccQ_Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ccQpein
github_username:  ccQpein
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
