# Site settings
title: ccQ's Blog
header-img: img/home-bg.jpg
email: ccq777@hotmail.com
description: "ccQ的博客"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ccQpein
github_username:  ccQpein
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
